plugins:
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 2.7

inherit_from:
  - https://dbdrive.github.io/triebwerk/rubocop_common.yml

RSpec/NestedGroups:
  Exclude:
    - 'spec/lib/airship/api/base_spec.rb'
