require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4

inherit_from:
  - https://dbdrive.github.io/triebwerk/rubocop_common.yml

RSpec/NestedGroups:
  Exclude:
    - 'spec/lib/airship/api/base_spec.rb'
